######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 23 16:23:25 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
QMAKE_CXXFLAGS += -std=c++1y

# Input
HEADERS += src/foo.h
SOURCES += src/main.cpp
